### ISSUE TITLE
Methods for Derived Layers

### ISSUE THREAD

**Issue by madisonkh** [gswcm/CSCI4310_FA17_P2#2]
There needs to be a decision made on what methods we need for the derived layer classes (application, transport, network, link, and physical). What methods from the base layer class can be brought into the derived classes without changes and what methods need to be altered/introduced?

**Comment by Nafruoy** [comment]
I think the methods currently in the layer class can be brought over with very little, if any, trouble except possibly setUpper for the layers being used at the top most levels (application for host, network - router, ). 

Trying to implement a blanket solution to that may be a hassle since a network or link layer isn't always the top, and it may not even be a problem since we can just leave it alone. I'm fine with either though.

**Comment by madisonkh** [comment]
The stack classes handle setting up the relationships between the layers using setUpper and setLower, so all the layers need is the setter methods already found in the Layers class.
